### ISSUE TITLE
Ubuntu 16.10 support

### ISSUE THREAD

**Issue by tes5884** [andrewsomething/digitalocean-indicator#13]
Can we please get 16.10 support?

Thanks!!

**Comment by aensley** [comment]
It _almost_ works for me on 16.10. I thought installing `python-webkit` would fix the `ValueError: Namespace WebKit not available` error. But it didn't.

#### Installation

```ShellSession
aensley@home:~$ sudo add-apt-repository ppa:andrewsomething/digitalocean
[sudo] password for aensley: 
 Debian packaging for DigitalOcean tools.
 More info: https://launchpad.net/~andrewsomething/+archive/ubuntu/digitalocean
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmpwwuu7pvg/pubring.gpg' created
gpg: /tmp/tmpwwuu7pvg/trustdb.gpg: trustdb created
gpg: key CA1F91146F087E5A: public key "Launchpad PPA for Andrew Starr-Bochicchio" imported
gpg: Total number processed: 1
gpg:               imported: 1
OK
aensley@home:~$ sudo apt update && sudo apt install digitalocean-indicator
Hit:1 http://us.archive.ubuntu.com/ubuntu yakkety InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu yakkety-updates InRelease                                                                                               
Hit:3 http://us.archive.ubuntu.com/ubuntu yakkety-backports InRelease                                                                                                       
Get:4 http://security.ubuntu.com/ubuntu yakkety-security InRelease [102 kB]                                                                                                 
Get:6 http://ppa.launchpad.net/andrewsomething/digitalocean/ubuntu yakkety InRelease [17.6 kB]                                                         
Hit:7 http://repo.sinew.in stable InRelease                                                                                       
Hit:8 http://ppa.launchpad.net/simon-cadman/niftyrepo/ubuntu yakkety InRelease                                       
Get:9 http://ppa.launchpad.net/andrewsomething/digitalocean/ubuntu yakkety/main amd64 Packages [788 B]
Get:10 http://ppa.launchpad.net/andrewsomething/digitalocean/ubuntu yakkety/main i386 Packages [788 B]
Get:11 http://ppa.launchpad.net/andrewsomething/digitalocean/ubuntu yakkety/main Translation-en [596 B]
Fetched 122 kB in 1s (72.0 kB/s)         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
8 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  python-digitalocean python-ndg-httpsclient python-openssl python-requests python-urllib3
Suggested packages:
  python-openssl-doc python-openssl-dbg python-socks python-ntlm
The following NEW packages will be installed:
  digitalocean-indicator python-digitalocean python-ndg-httpsclient python-openssl python-requests python-urllib3
0 upgraded, 6 newly installed, 0 to remove and 8 not upgraded.
Need to get 218 kB of archives.
After this operation, 1,077 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu yakkety/main amd64 python-urllib3 all 1.15.1-2 [60.3 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu yakkety/main amd64 python-requests all 2.10.0-2 [57.2 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu yakkety/main amd64 python-openssl all 16.1.0-1 [37.6 kB]
Get:4 http://ppa.launchpad.net/andrewsomething/digitalocean/ubuntu yakkety/main amd64 python-digitalocean all 1.10.1-0~andrewsomething1 [17.7 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu yakkety/main amd64 python-ndg-httpsclient all 0.4.2-1 [25.5 kB]
Get:6 http://ppa.launchpad.net/andrewsomething/digitalocean/ubuntu yakkety/main amd64 digitalocean-indicator all 0.3-0~andrewsomething1 [19.2 kB]
Fetched 218 kB in 0s (255 kB/s)                   
Selecting previously unselected package python-urllib3.
(Reading database ... 270397 files and directories currently installed.)
Preparing to unpack .../0-python-urllib3_1.15.1-2_all.deb ...
Unpacking python-urllib3 (1.15.1-2) ...
Selecting previously unselected package python-requests.
Preparing to unpack .../1-python-requests_2.10.0-2_all.deb ...
Unpacking python-requests (2.10.0-2) ...
Selecting previously unselected package python-digitalocean.
Preparing to unpack .../2-python-digitalocean_1.10.1-0~andrewsomething1_all.deb ...
Unpacking python-digitalocean (1.10.1-0~andrewsomething1) ...
Selecting previously unselected package python-openssl.
Preparing to unpack .../3-python-openssl_16.1.0-1_all.deb ...
Unpacking python-openssl (16.1.0-1) ...
Selecting previously unselected package python-ndg-httpsclient.
Preparing to unpack .../4-python-ndg-httpsclient_0.4.2-1_all.deb ...
Unpacking python-ndg-httpsclient (0.4.2-1) ...
Selecting previously unselected package digitalocean-indicator.
Preparing to unpack .../5-digitalocean-indicator_0.3-0~andrewsomething1_all.deb ...
Unpacking digitalocean-indicator (0.3-0~andrewsomething1) ...
Setting up python-urllib3 (1.15.1-2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu1) ...
Setting up python-openssl (16.1.0-1) ...
Processing triggers for libglib2.0-0:amd64 (2.50.2-2ubuntu1) ...
Processing triggers for bamfdaemon (0.5.3+16.10.20160929-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Setting up python-requests (2.10.0-2) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu4) ...
Processing triggers for hicolor-icon-theme (0.15-1) ...
Setting up python-ndg-httpsclient (0.4.2-1) ...
Setting up python-digitalocean (1.10.1-0~andrewsomething1) ...
Setting up digitalocean-indicator (0.3-0~andrewsomething1) ...
aensley@home:~$ 
```

#### First run

```ShellSession
aensley@home:~$ /usr/bin/digitalocean-indicator 
Traceback (most recent call last):
  File "/usr/bin/digitalocean-indicator", line 45, in <module>
    import digitalocean_indicator
  File "/usr/lib/python2.7/dist-packages/digitalocean_indicator/__init__.py", line 24, in <module>
    from digitalocean_indicator import DoIndicator
  File "/usr/lib/python2.7/dist-packages/digitalocean_indicator/DoIndicator.py", line 31, in <module>
    from digitalocean_indicator.DoPreferencesDialog import DoPreferencesDialog
  File "/usr/lib/python2.7/dist-packages/digitalocean_indicator/DoPreferencesDialog.py", line 37, in <module>
    from digitalocean_indicator.OAuthWindow import AuthWin
  File "/usr/lib/python2.7/dist-packages/digitalocean_indicator/OAuthWindow.py", line 4, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available
aensley@home:~$
```

#### Trying to fix error

```ShellSession
aensley@home:~$ sudo apt install python-webkit
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libjavascriptcoregtk-1.0-0 libwebkitgtk-1.0-0
The following NEW packages will be installed:
  libjavascriptcoregtk-1.0-0 libwebkitgtk-1.0-0 python-webkit
0 upgraded, 3 newly installed, 0 to remove and 8 not upgraded.
Need to get 9,791 kB of archives.
After this operation, 42.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu yakkety/universe amd64 libjavascriptcoregtk-1.0-0 amd64 2.4.11-3 [1,831 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu yakkety/universe amd64 libwebkitgtk-1.0-0 amd64 2.4.11-3 [7,934 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu yakkety/universe amd64 python-webkit amd64 1.1.8-3.1 [25.5 kB]                                                                                                          
Fetched 9,791 kB in 10s (923 kB/s)                                                                                                                                                                                
Selecting previously unselected package libjavascriptcoregtk-1.0-0:amd64.
(Reading database ... 270578 files and directories currently installed.)
Preparing to unpack .../0-libjavascriptcoregtk-1.0-0_2.4.11-3_amd64.deb ...
Unpacking libjavascriptcoregtk-1.0-0:amd64 (2.4.11-3) ...
Selecting previously unselected package libwebkitgtk-1.0-0:amd64.
Preparing to unpack .../1-libwebkitgtk-1.0-0_2.4.11-3_amd64.deb ...
Unpacking libwebkitgtk-1.0-0:amd64 (2.4.11-3) ...
Selecting previously unselected package python-webkit.
Preparing to unpack .../2-python-webkit_1.1.8-3.1_amd64.deb ...
Unpacking python-webkit (1.1.8-3.1) ...
Setting up libjavascriptcoregtk-1.0-0:amd64 (2.4.11-3) ...
Processing triggers for libc-bin (2.24-3ubuntu2) ...
Setting up libwebkitgtk-1.0-0:amd64 (2.4.11-3) ...
Setting up python-webkit (1.1.8-3.1) ...
Processing triggers for libc-bin (2.24-3ubuntu2) ...
aensley@home:~$
```

#### Still dead

```ShellSession
aensley@home:~$ /usr/bin/digitalocean-indicator 
Traceback (most recent call last):
  File "/usr/bin/digitalocean-indicator", line 45, in <module>
    import digitalocean_indicator
  File "/usr/lib/python2.7/dist-packages/digitalocean_indicator/__init__.py", line 24, in <module>
    from digitalocean_indicator import DoIndicator
  File "/usr/lib/python2.7/dist-packages/digitalocean_indicator/DoIndicator.py", line 31, in <module>
    from digitalocean_indicator.DoPreferencesDialog import DoPreferencesDialog
  File "/usr/lib/python2.7/dist-packages/digitalocean_indicator/DoPreferencesDialog.py", line 37, in <module>
    from digitalocean_indicator.OAuthWindow import AuthWin
  File "/usr/lib/python2.7/dist-packages/digitalocean_indicator/OAuthWindow.py", line 4, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available
aensley@home:~$ 
```

**Comment by andrewsomething** [comment]
@aensley It looks like the package should have a dependency on `gir1.2-webkit-3.0` Installing that should resolve the issue  (See: #16). I'll try to find some time to make a new upload soon.

**Comment by aensley** [comment]
@andrewsomething Yup! That did it! Thanks for the quick response. I'm now using this on Ubuntu 16.10!

```ShellSession
aensley@home:~$ sudo apt install gir1.2-webkit-3.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  gir1.2-javascriptcoregtk-3.0 libjavascriptcoregtk-3.0-0 libwebkitgtk-3.0-0
The following NEW packages will be installed:
  gir1.2-javascriptcoregtk-3.0 gir1.2-webkit-3.0 libjavascriptcoregtk-3.0-0 libwebkitgtk-3.0-0
0 upgraded, 4 newly installed, 0 to remove and 8 not upgraded.
Need to get 9,838 kB of archives.
After this operation, 43.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu yakkety/universe amd64 gir1.2-javascriptcoregtk-3.0 amd64 2.4.11-3 [13.5 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu yakkety/universe amd64 libjavascriptcoregtk-3.0-0 amd64 2.4.11-3 [1,831 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu yakkety/universe amd64 libwebkitgtk-3.0-0 amd64 2.4.11-3 [7,933 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu yakkety/universe amd64 gir1.2-webkit-3.0 amd64 2.4.11-3 [60.5 kB]                                                                                                       
Fetched 9,838 kB in 10s (940 kB/s)                                                                                                                                                                                
Selecting previously unselected package gir1.2-javascriptcoregtk-3.0:amd64.
(Reading database ... 237752 files and directories currently installed.)
Preparing to unpack .../0-gir1.2-javascriptcoregtk-3.0_2.4.11-3_amd64.deb ...
Unpacking gir1.2-javascriptcoregtk-3.0:amd64 (2.4.11-3) ...
Selecting previously unselected package libjavascriptcoregtk-3.0-0:amd64.
Preparing to unpack .../1-libjavascriptcoregtk-3.0-0_2.4.11-3_amd64.deb ...
Unpacking libjavascriptcoregtk-3.0-0:amd64 (2.4.11-3) ...
Selecting previously unselected package libwebkitgtk-3.0-0:amd64.
Preparing to unpack .../2-libwebkitgtk-3.0-0_2.4.11-3_amd64.deb ...
Unpacking libwebkitgtk-3.0-0:amd64 (2.4.11-3) ...
Selecting previously unselected package gir1.2-webkit-3.0:amd64.
Preparing to unpack .../3-gir1.2-webkit-3.0_2.4.11-3_amd64.deb ...
Unpacking gir1.2-webkit-3.0:amd64 (2.4.11-3) ...
Setting up gir1.2-javascriptcoregtk-3.0:amd64 (2.4.11-3) ...
Setting up libjavascriptcoregtk-3.0-0:amd64 (2.4.11-3) ...
Processing triggers for libc-bin (2.24-3ubuntu2) ...
Setting up libwebkitgtk-3.0-0:amd64 (2.4.11-3) ...
Setting up gir1.2-webkit-3.0:amd64 (2.4.11-3) ...
Processing triggers for libc-bin (2.24-3ubuntu2) ...
aensley@home:~$
```

**Comment by jalcine** [comment]
I'm bumping this again to see if support for Ubuntu 17.10 is on the roadmap.
