### ISSUE TITLE
ValueError: Namespace WebKit not available

### ISSUE THREAD

**Issue by pacotole** [andrewsomething/digitalocean-indicator#16]
I'm using Elementary OS 0.4 Loki built on "Ubuntu 16.04 LTS" and get this error:

```
Traceback (most recent call last):
  File "/usr/bin/digitalocean-indicator", line 45, in <module>
    import digitalocean_indicator
  File "/usr/lib/python2.7/dist-packages/digitalocean_indicator/__init__.py", line 24, in <module>
    from digitalocean_indicator import DoIndicator
  File "/usr/lib/python2.7/dist-packages/digitalocean_indicator/DoIndicator.py", line 31, in <module>
    from digitalocean_indicator.DoPreferencesDialog import DoPreferencesDialog
  File "/usr/lib/python2.7/dist-packages/digitalocean_indicator/DoPreferencesDialog.py", line 37, in <module>
    from digitalocean_indicator.OAuthWindow import AuthWin
  File "/usr/lib/python2.7/dist-packages/digitalocean_indicator/OAuthWindow.py", line 4, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available
```

**Comment by andrewsomething** [comment]
Hi! Thanks for the report. How did you install digitalocean-indicator? Do you have the package `gir1.2-webkit-3.0` It's installed on Ubuntu 16.04 by default, but possibly not Elementary. We should probably add an explicit dependency.

**Comment by pacotole** [comment]
Installing the package `gir1.2-webkit-3.0` solved the problem. Thanks!

**Comment by yogi-satya** [comment]
I have the same problem in Fedora 29

```
Traceback (most recent call last):
  File "/usr/bin/remarkable", line 65, in <module>
    import remarkable
  File "/usr/lib/python3/dist-packages/remarkable/__init__.py", line 30, in <module>
    from remarkable import RemarkableWindow
  File "/usr/lib/python3/dist-packages/remarkable/RemarkableWindow.py", line 27, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available
```
